# Generated by Django 4.1.6 on 2023-12-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic_survival_api', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogue',
            old_name='mensaje',
            new_name='message',
        ),
    ]
