# Generated by Django 4.1.6 on 2023-12-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_survival_api', '0003_rename_mensaje_dialogue_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='message',
            field=models.CharField(max_length=2200),
        ),
        migrations.AlterField(
            model_name='player',
            name='hp',
            field=models.IntegerField(),
        ),
    ]
